### ISSUE TITLE
Segfaults after making HElib with FHE_DCRT_THREADS and FHE_BOOT_THREADS

### ISSUE THREAD

**Issue by zxexz** [homenc/HElib#58] opened 2015-05-07 20:17 UTC
After making with FHE_DCRT_THREADS, segfaults at the first ./Test_General_x in the make check. (don't have the logs, can post later).

After making with FHE_BOOT_THREADS: 
./Test_EvalMap_x mvec="[7 3 221]" gens="[3979 3095 3760]" ords="[6 2 -8]"
**\* TestIt: p=2, r=1, c=2, k=80, w=64, L=6, mvec=[7 3 221]
m = 4641, p = 2, phi(m) = 2304
  ord(p)=24
  generator 3979 has order (== Z_m^_) of 6
  generator 3095 has order (== Z_m^_) of 2
  generator 3760 has order (!= Z_m^*) of 8
  T = [1 3760 1114 2458 1849 22 3823 1303 3095 2213 4208 911 302 3116 2276 4397 3979 3097 451 1795 1186 4000 3160 640 2432 1550 3545 248 4280 2453 1613 3734 1990 1108 3103 4447 3838 2011 1171 3292 443 4202 1556 2900 2291 464 4265 1745 664 4423 1777 3121 2512 685 4486 1966 3758 2876 230 1574 965 3779 2939 419 1327 445 2440 3784 3175 1348 508 2629 4421 3539 893 2237 1628 4442 3602 1082 3316 2434 4429 1132 523 3337 2497 4618 1769 887 2882 4226 3617 1790 950 3071 ]

generating key-switching matrices... done
  init, level=4, log(noise/modulus)~-66.4259
build EvalMap
apply EvalMap
Segmentation fault (core dumped)

make checks succeed without either option with these CFLAGS:
CFLAGS = -g -O2 -std=c++11 -DEVALMAP_CACHED=1 -pthread -DFHE_THREADS

My system is an x86_64 (i7), running 64 bit kernel (3.19.5-200.fc21.x86_64).  Fedora 21 chrooted into an Ubuntu 14.04 dev environment.

**Comment by victorshoup** [comment] 2015-05-07 20:35
Can you check if ntl was built with threads enabled? Not sure if helib explicitly checks for this. It probably should. Also, you'll need gcc 4.9+ if this is going to work at all 

zxexz <notifications@github.com> wrote:
>After making with FHE_DCRT_THREADS, segfaults at the first
>./Test_General_x in the make check. (don't have the logs, can post
>later).
> 
>After making with FHE_BOOT_THREADS: 
>./Test_EvalMap_x mvec="[7 3 221]" gens="[3979 3095 3760]" ords="[6 2
>-8]"
>*** TestIt: p=2, r=1, c=2, k=80, w=64, L=6, mvec=[7 3 221]
>m = 4641, p = 2, phi(m) = 2304
>  ord(p)=24
>  generator 3979 has order (== Z_m^*) of 6
>  generator 3095 has order (== Z_m^*) of 2
>  generator 3760 has order (!= Z_m^*) of 8
>T = [1 3760 1114 2458 1849 22 3823 1303 3095 2213 4208 911 302 3116
>2276 4397 3979 3097 451 1795 1186 4000 3160 640 2432 1550 3545 248 4280
>2453 1613 3734 1990 1108 3103 4447 3838 2011 1171 3292 443 4202 1556
>2900 2291 464 4265 1745 664 4423 1777 3121 2512 685 4486 1966 3758 2876
>230 1574 965 3779 2939 419 1327 445 2440 3784 3175 1348 508 2629 4421
>3539 893 2237 1628 4442 3602 1082 3316 2434 4429 1132 523 3337 2497
>4618 1769 887 2882 4226 3617 1790 950 3071 ]
>
>generating key-switching matrices... done
>  init, level=4, log(noise/modulus)~-66.4259
>build EvalMap
>apply EvalMap
>Segmentation fault (core dumped)
>
>make checks succeed without either option with these CFLAGS:
>CFLAGS = -g -O2 -std=c++11 -DEVALMAP_CACHED=1 -pthread -DFHE_THREADS
>
>My system is an x86_64 (i7), running 64 bit kernel
>(3.19.5-200.fc21.x86_64).  Fedora 21 chrooted into an Ubuntu 14.04 dev
>environment.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/shaih/HElib/issues/58

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zxexz** [comment] 2015-06-24 18:07
Sorry for taking so long to get back.  The problem seems to come from -DEVALMAP_CACHED=1, HElib compiles and the checks succeed without it.  Does this mean there could be issues with using doubleCRTs?  I'm using GCC 4.9.2, GMP 6.0.0, and NTL 9.2.0 (build with threads enabled).

**Comment by victorshoup** [comment] 2015-06-24 18:38
Hmmm...that does seem odd.  Can you tell me which other test programs succeed/fail in make check?
It might take me a while to get everything configured to check this on my own machine...the multi-threading stuff is pretty bleeding edge...but it's supposed to work...

**Comment by victorshoup** [comment] 2015-06-24 22:33
Wait. I think the problem is just that the way the library is currently set up, all the thread related stuff
is experimental.... in particular, there is a global thread-pool object that is initially NULL and needs 
to be initialized in main(). Right now, I think the only program that does this is Test_bootstrapping.
You can look there to see how it should be initialized.

**Comment by faberga** [comment] 2019-09-17 10:24
Closing as this issue is very old now and was reported against a much older version of HElib, and it is unclear if it is still present.  Please re-open if this still occurs when using the minimum versions of compiler, GMP, and NTL as specified in INSTALL.md

**Closed by faberga** 2019-09-17 10:24 UTC
